# Version of the Hinata theme that is currently used
version: 0.0.1
# Path or URL to the website's icon
favicon: /images/favicon.ico
# Path or URL to RSS atom.xml
rss: rss2.xml
# Path or URL to the website's logo to be shown on the left of the navigation bar or footer
logo: /images/logo.png
# Navigation bar link settings
navigation:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  About: /about