# Version of the Hinata theme that is currently used
version: 0.0.1
# Path or URL to the website's icon
favicon: /images/favicon.ico
# Path or URL to RSS atom.xml
rss: rss2.xml
# Path or URL to the website's logo to be shown on the left of the navigation bar or footer
# logo: /images/logo.png
# Navigation bar link settings
navigation:
    Home: /
    Archives: /archives
    Categories: /categories
    Tags: /tags
    About: /about
# Footer section link settings
footer:
    Follow Me:
        Weibo: https://www.weibo.com
        Zhihu: https://www.zhihu.com
        Instagram: https://www.instagram.com
        Twitter: https://twitter.com
        Github: https://github.com/gylidian
    Resources:
        Designmodo: //designmodo.com/
        Jenkov: //tutorials.jenkov.com/
        Tympanus.net: //tympanus.net/codrops/
        Uisdc: //www.uisdc.com/
        scotch.io: //scotch.io
        css-tricks: //css-tricks.com
    My Friends:
        Demo1: https://github.com/gylidian
        Demo2: https://github.com/gylidian
        Demo3: https://github.com/gylidian
        Demo4: https://github.com/gylidian
        Demo5: https://github.com/gylidian
# Article display settings
article:
  # Whether to show article thumbnail images
  thumbnail: true
  # Whether to show estimate article reading time
  readtime: true
# Sns Link icon settings
sns: 
  facebook: 
    icon: fb
    url: https://www.facebook.com
  google plus: 
    icon: gp
    url: https://plus.google.com
  github:
    icon: github
    url: https://github.com/gylidian
  instagram:
    icon: ins
    url: https://www.instagram.com
  behance:
    icon: be
    url: https://www.behance.net